"use client";

import {
  AccountBalance,
  AccountBalanceWallet,
  AccountCircle,
  AccountTree,
  AdminPanelSettings,
  Analytics,
  Apartment,
  Article,
  Assessment,
  Assignment,
  AssignmentInd,
  AssignmentTurnedIn,
  AttachMoney,
  Badge,
  BarChart,
  Biotech,
  Bloodtype,
  Bookmark,
  Build,
  Business,
  CalendarMonth,
  CalendarToday,
  Cancel,
  CardGiftcard,
  CardMembership,
  Category,
  Chat,
  CheckCircle,
  Checklist,
  CleaningServices,
  CloudDownload,
  CloudUpload,
  Computer,
  ContactMail,
  ContactPhone,
  CreditCard,
  CreditScore,
  CreditScoreOutlined,
  CurrencyExchange,
  Dashboard,
  DashboardOutlined,
  DateRange,
  Delete,
  Description,
  Discount,
  DisplaySettings,
  Domain,
  DonutLarge,
  Download,
  Edit,
  Email,
  Emergency,
  Engineering,
  Event,
  EventAvailable,
  EventNote,
  Explore,
  FactCheck,
  Favorite,
  FiberManualRecord,
  FilterList,
  Flag,
  FlightTakeoff,
  Folder,
  FolderOpen,
  Forum,
  FormatListBulleted,
  GavelOutlined,
  Grading,
  Group,
  Groups,
  Handshake,
  HandshakeOutlined,
  Handyman,
  Healing,
  HealthAndSafety,
  Help,
  History,
  Home,
  Info,
  InsertChart,
  Inventory,
  Inventory2,
  Key,
  Launch,
  Leaderboard,
  ListAlt,
  LocalAtm,
  LocalHospital,
  LocalOffer,
  LocalPharmacy,
  LocationOn,
  Lock,
  LockOpen,
  Loyalty,
  Mail,
  ManageAccounts,
  Map as MapIcon,
  Medication,
  MedicalInformation,
  MedicalServices,
  Menu as MenuIcon,
  MiscellaneousServices,
  Money,
  MonitorHeart,
  MyLocation,
  Notifications,
  NotificationsActive,
  Password,
  Payment,
  Payments,
  People,
  PeopleAlt,
  Person,
  PersonAdd,
  Phone,
  PieChart,
  Place,
  PointOfSale,
  Print,
  Public,
  QrCode,
  Receipt,
  ReceiptLong,
  Redeem,
  Refresh,
  RequestQuote,
  RestaurantOutlined,
  Savings,
  Schedule,
  School,
  Science,
  Search,
  Security,
  Sell,
  Settings,
  SettingsOutlined,
  SettingsSuggest,
  Share,
  Shield,
  ShoppingBag,
  ShoppingCart,
  ShowChart,
  Sms,
  Sort,
  Spa,
  StackedLineChart,
  Star,
  Store,
  Storefront,
  StorefrontOutlined,
  SupportAgent,
  Sync,
  TableChart,
  Task,
  Timeline,
  Today,
  TrendingDown,
  TrendingUp,
  Tune,
  Upload,
  Vaccines,
  Verified,
  VerifiedUser,
  Visibility,
  Wallet,
  Warning,
  Work,
} from "@mui/icons-material";

/**
 * Ánh xạ tên Icon lưu trong DB (SysMenus.Icon) sang component icon của MUI.
 * Một số tên là custom (Setting, LineChart, Desktop...) nên map thủ công.
 */
const ICONS = {
  // ==== Alias tên custom / tên có hậu tố "Icon" trong DB cũ ====
  BulletList: FormatListBulleted,
  CardGift: CardGiftcard,
  CardMember: CardMembership,
  CreditScoreOutlinedIcon: CreditScoreOutlined,
  CurrencyExchangeIcon: CurrencyExchange,
  DashboardOutlinedIcon: DashboardOutlined,
  Desktop: Computer,
  GavelOutlinedIcon: GavelOutlined,
  HandshakeOutlinedIcon: HandshakeOutlined,
  LineChart: ShowChart,
  Menus: MenuIcon,
  Partner: Handshake,
  RestaurantOutlinedIcon: RestaurantOutlined,
  Setting: Settings,
  SettingsOutlinedIcon: SettingsOutlined,
  StorefrontOutlinedIcon: StorefrontOutlined,

  // ==== Tên chuẩn MUI ====
  AccountBalance,
  AccountBalanceWallet,
  AccountCircle,
  AccountTree,
  AdminPanelSettings,
  Analytics,
  Apartment,
  Article,
  Assessment,
  Assignment,
  AssignmentInd,
  AssignmentTurnedIn,
  AttachMoney,
  Badge,
  BarChart,
  Biotech,
  Bloodtype,
  Bookmark,
  Build,
  Business,
  CalendarMonth,
  CalendarToday,
  Cancel,
  CardGiftcard,
  CardMembership,
  Category,
  Chat,
  CheckCircle,
  Checklist,
  CleaningServices,
  CloudDownload,
  CloudUpload,
  Computer,
  ContactMail,
  ContactPhone,
  CreditCard,
  CreditScore,
  CreditScoreOutlined,
  CurrencyExchange,
  Dashboard,
  DashboardOutlined,
  DateRange,
  Delete,
  Description,
  Discount,
  DisplaySettings,
  Domain,
  DonutLarge,
  Download,
  Edit,
  Email,
  Emergency,
  Engineering,
  Event,
  EventAvailable,
  EventNote,
  Explore,
  FactCheck,
  Favorite,
  FilterList,
  Flag,
  FlightTakeoff,
  Folder,
  FolderOpen,
  Forum,
  FormatListBulleted,
  GavelOutlined,
  Grading,
  Group,
  Groups,
  Handshake,
  HandshakeOutlined,
  Handyman,
  Healing,
  HealthAndSafety,
  Help,
  History,
  Home,
  Info,
  InsertChart,
  Inventory,
  Inventory2,
  Key,
  Launch,
  Leaderboard,
  ListAlt,
  LocalAtm,
  LocalHospital,
  LocalOffer,
  LocalPharmacy,
  LocationOn,
  Lock,
  LockOpen,
  Loyalty,
  Mail,
  ManageAccounts,
  Map: MapIcon,
  Medication,
  MedicalInformation,
  MedicalServices,
  Menu: MenuIcon,
  MiscellaneousServices,
  Money,
  MonitorHeart,
  MyLocation,
  Notifications,
  NotificationsActive,
  Password,
  Payment,
  Payments,
  People,
  PeopleAlt,
  Person,
  PersonAdd,
  Phone,
  PieChart,
  Place,
  PointOfSale,
  Print,
  Public,
  QrCode,
  Receipt,
  ReceiptLong,
  Redeem,
  Refresh,
  RequestQuote,
  RestaurantOutlined,
  Savings,
  Schedule,
  School,
  Science,
  Search,
  Security,
  Sell,
  Settings,
  SettingsOutlined,
  SettingsSuggest,
  Share,
  Shield,
  ShoppingBag,
  ShoppingCart,
  ShowChart,
  Sms,
  Sort,
  Spa,
  StackedLineChart,
  Star,
  Store,
  Storefront,
  StorefrontOutlined,
  SupportAgent,
  Sync,
  TableChart,
  Task,
  Timeline,
  Today,
  TrendingDown,
  TrendingUp,
  Tune,
  Upload,
  Vaccines,
  Verified,
  VerifiedUser,
  Visibility,
  Wallet,
  Warning,
  Work,
};

/** Icon mặc định khi không có/không khớp */
export const DefaultIcon = FiberManualRecord;

/** Danh sách tên icon hỗ trợ (để chọn trong dropdown) */
export const iconNames = Object.keys(ICONS).sort();

export function resolveIcon(name) {
    if (!name) return DefaultIcon;
    return ICONS[name.trim()] || DefaultIcon;
}
