import { palette as basePalette } from "@/palette";

const statusColors = {
  warning: basePalette.warning,
  info: basePalette.info,
  success: basePalette.success,
  error: basePalette.error,
};

export const themePresets = {
  retro: {
    ...basePalette,
    primary: { main: "#C2410C", light: "#EA580C", dark: "#9A3412", contrastText: "#FFFFFF" },
    secondary: { main: "#D97706", light: "#F59E0B", dark: "#B45309", contrastText: "#FFFFFF" },
    background: { default: "#FFF7ED", paper: "#FFFFFF" },
    text: { primary: "#431407", secondary: "#7C2D12", disabled: "#A8A29E" },
    divider: "#FED7AA",
    ...statusColors,
  },
  neutral: {
    ...basePalette,
    primary: { main: "#475569", light: "#64748B", dark: "#334155", contrastText: "#FFFFFF" },
    secondary: { main: "#64748B", light: "#94A3B8", dark: "#475569", contrastText: "#FFFFFF" },
    background: { default: "#F8FAFC", paper: "#FFFFFF" },
    text: { primary: "#0F172A", secondary: "#475569", disabled: "#94A3B8" },
    divider: "#E2E8F0",
    ...statusColors,
  },
  blue: {
    ...basePalette,
    primary: { main: "#2563EB", light: "#3B82F6", dark: "#1D4ED8", contrastText: "#FFFFFF" },
    secondary: { main: "#EA580C", light: "#F97316", dark: "#C2410C", contrastText: "#FFFFFF" },
    background: { default: "#F8FAFC", paper: "#FFFFFF" },
    text: { primary: "#1E293B", secondary: "#475569", disabled: "#94A3B8" },
    divider: "#DBEAFE",
    ...statusColors,
  },
  indigo: {
    ...basePalette,
    primary: { main: "#4F46E5", light: "#818CF8", dark: "#3730A3", contrastText: "#FFFFFF" },
    secondary: { main: "#D97706", light: "#F59E0B", dark: "#B45309", contrastText: "#FFFFFF" },
    background: { default: "#F8FAFC", paper: "#FFFFFF" },
    text: { primary: "#1E1B4B", secondary: "#475569", disabled: "#94A3B8" },
    divider: "#E0E7FF",
    ...statusColors,
  },
  ocean: {
    ...basePalette,
    primary: { main: "#0891B2", light: "#22D3EE", dark: "#0E7490", contrastText: "#FFFFFF" },
    secondary: { main: "#0369A1", light: "#0EA5E9", dark: "#075985", contrastText: "#FFFFFF" },
    background: { default: "#ECFEFF", paper: "#FFFFFF" },
    text: { primary: "#164E63", secondary: "#0E7490", disabled: "#94A3B8" },
    divider: "#A5F3FC",
    ...statusColors,
  },
  rose: {
    ...basePalette,
    primary: { main: "#BE123C", light: "#F43F5E", dark: "#9F1239", contrastText: "#FFFFFF" },
    secondary: { main: "#DB2777", light: "#EC4899", dark: "#BE185D", contrastText: "#FFFFFF" },
    background: { default: "#FFF1F2", paper: "#FFFFFF" },
    text: { primary: "#4C0519", secondary: "#881337", disabled: "#A8A29E" },
    divider: "#FECDD3",
    ...statusColors,
  },
  midnight: {
    ...basePalette,
    mode: "dark",
    primary: { main: "#60A5FA", light: "#93C5FD", dark: "#2563EB", contrastText: "#0F172A" },
    secondary: { main: "#94A3B8", light: "#CBD5E1", dark: "#64748B", contrastText: "#0F172A" },
    background: { default: "#0F172A", paper: "#1E293B" },
    text: { primary: "#F8FAFC", secondary: "#CBD5E1", disabled: "#64748B" },
    divider: "#334155",
    ...statusColors,
  },
  lavender: {
    ...basePalette,
    primary: { main: "#7C3AED", light: "#A78BFA", dark: "#5B21B6", contrastText: "#FFFFFF" },
    secondary: { main: "#C026D3", light: "#E879F9", dark: "#A21CAF", contrastText: "#FFFFFF" },
    background: { default: "#FAF5FF", paper: "#FFFFFF" },
    text: { primary: "#2E1065", secondary: "#6B21A8", disabled: "#A8A29E" },
    divider: "#E9D5FF",
    ...statusColors,
  },
  coffee: {
    ...basePalette,
    primary: { main: "#78350F", light: "#A16207", dark: "#451A03", contrastText: "#FFFFFF" },
    secondary: { main: "#B45309", light: "#D97706", dark: "#92400E", contrastText: "#FFFFFF" },
    background: { default: "#FFFBEB", paper: "#FFFFFF" },
    text: { primary: "#451A03", secondary: "#78350F", disabled: "#A8A29E" },
    divider: "#FDE68A",
    ...statusColors,
  },
  sunset: {
    ...basePalette,
    primary: { main: "#E11D48", light: "#FB7185", dark: "#9F1239", contrastText: "#FFFFFF" },
    secondary: { main: "#EA580C", light: "#FB923C", dark: "#C2410C", contrastText: "#FFFFFF" },
    background: { default: "#FFF1F2", paper: "#FFFFFF" },
    text: { primary: "#4C0519", secondary: "#881337", disabled: "#A8A29E" },
    divider: "#FECDD3",
    ...statusColors,
  },
  sky: {
    ...basePalette,
    primary: { main: "#0284C7", light: "#38BDF8", dark: "#0369A1", contrastText: "#FFFFFF" },
    secondary: { main: "#0EA5E9", light: "#7DD3FC", dark: "#0284C7", contrastText: "#FFFFFF" },
    background: { default: "#F0F9FF", paper: "#FFFFFF" },
    text: { primary: "#0C4A6E", secondary: "#0369A1", disabled: "#94A3B8" },
    divider: "#BAE6FD",
    ...statusColors,
  },
  mint: {
    ...basePalette,
    primary: { main: "#0F766E", light: "#2DD4BF", dark: "#115E59", contrastText: "#FFFFFF" },
    secondary: { main: "#14B8A6", light: "#5EEAD4", dark: "#0F766E", contrastText: "#0F172A" },
    background: { default: "#F0FDFA", paper: "#FFFFFF" },
    text: { primary: "#134E4A", secondary: "#0F766E", disabled: "#94A3B8" },
    divider: "#99F6E4",
    ...statusColors,
  },
  peach: {
    ...basePalette,
    primary: { main: "#C2410C", light: "#FB923C", dark: "#9A3412", contrastText: "#FFFFFF" },
    secondary: { main: "#EA580C", light: "#FDBA74", dark: "#C2410C", contrastText: "#FFFFFF" },
    background: { default: "#FFF7ED", paper: "#FFFFFF" },
    text: { primary: "#431407", secondary: "#9A3412", disabled: "#A8A29E" },
    divider: "#FED7AA",
    ...statusColors,
  },
  lilac: {
    ...basePalette,
    primary: { main: "#6D28D9", light: "#A78BFA", dark: "#5B21B6", contrastText: "#FFFFFF" },
    secondary: { main: "#8B5CF6", light: "#C4B5FD", dark: "#6D28D9", contrastText: "#FFFFFF" },
    background: { default: "#F5F3FF", paper: "#FFFFFF" },
    text: { primary: "#2E1065", secondary: "#6D28D9", disabled: "#A8A29E" },
    divider: "#DDD6FE",
    ...statusColors,
  },
  lemon: {
    ...basePalette,
    primary: { main: "#A16207", light: "#EAB308", dark: "#854D0E", contrastText: "#FFFFFF" },
    secondary: { main: "#CA8A04", light: "#FACC15", dark: "#A16207", contrastText: "#1C1917" },
    background: { default: "#FEFCE8", paper: "#FFFFFF" },
    text: { primary: "#422006", secondary: "#713F12", disabled: "#A8A29E" },
    divider: "#FEF08A",
    ...statusColors,
  },
};

export const themeOptions = [
  { key: "neutral", label: "Neutral", color: "#475569" },
  { key: "blue", label: "Blue", color: "#2563EB" },
  { key: "indigo", label: "Indigo", color: "#4F46E5" },
  { key: "ocean", label: "Ocean", color: "#0891B2" },
  { key: "rose", label: "Rose", color: "#BE123C" },
  { key: "mint", label: "Mint", color: "#2DD4BF" },
  { key: "lilac", label: "Lilac", color: "#A78BFA" },
  { key: "sky", label: "Sky", color: "#38BDF8" },
  { key: "lemon", label: "Lemon", color: "#EAB308" },
];
